import NavBar from '../Components/navbar/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import EcommerceContextProvider from './Context/ecommerce'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={inter.className}>
        <EcommerceContextProvider>

            <NavBar/>
            {children}
        </EcommerceContextProvider>
        </body>
    </html>
  )
}
