import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Navbar/Navbar'
import ResponsiveDrawer from './Admin/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <ResponsiveDrawer Collection={{
          name: '',
          image: ''
        }} id={0} categoryname={''} image={''} Stock={0}/>
        {children}</body>
    </html>
  )
}
